config/routes.rb
Rails.application.routes.draw do
  resources :info_emails

  get 'sessions/new'

  get 'sessions/destroy'

  resources :posts do
    resources :comments
  end
  root "posts#index"
  resources :users
  resources :sessions

  get '/about', to: 'pages#about'
  get '/substitutions', to: 'pages#sub', as:"substitutions"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/info_email.rb
class InfoEmail < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_attached_file :photo, :styles => {:medium => "300x300" }
	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
	has_secure_password

	 has_attached_file :photo, :styles => { 

	 :medium => "300x300>", 

	 :thumb => "100x100>" }, 

	 :default_url => "/images/:style/missing.png"

	 validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
     @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		if current_user && current_user.is_admin 
	    @post = Post.find(params[:post_id])
	    @comment = @post.comments.find(params[:id])
	    @comment.destroy
	  end
 
  	redirect_to post_path(@post)
  end
end

app/controllers/info_emails_controller.rb
class InfoEmailsController < ApplicationController
  def index
    @info_emails = InfoEmail.all
  end

  def create
    @info_email = InfoEmail.new(params.require(:info_email).permit(:email))
    if @info_email.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end

	def sub
	end
	
end
	

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@current_user = current_user
		# @posts = Post.all.order('created_at DESC')

		#limited search for one column
    if params[:search].present?
      @posts = Post.where("body ilike ?", "%#{params[:search]}%")
    else
      @posts = Post.all.order('created_at DESC')
    end

    respond_to do |format|
    	format.html{}
    	format.json{ render json: @posts.map(&:body)}
    end

	end
	
	def new
			# if current_user && current_user.is_admin 
      	@post = Post.new
      # else
      # 	redirect_to posts_path
      # end
   end

	def create
		@post = Post.new(post_params)
      if @post.save
        redirect_to @post
      else
        render 'new'
      end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(params[:post].permit(:title, :body))
			# @post.update(post_params)
			redirect_to @post
		else render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :photo, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    @is_login = true
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to users_path, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

    

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end 
end

app/controllers/substitutions_controller.rb
class SubstitutionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < SessionsController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        #session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/info_emails_helper.rb
module InfoEmailsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/substitutions_helper.rb
module SubstitutionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>

  <p><%= link_to 'Delete', [comment.post, comment],
    method: :delete,
    class: "button",
    data: { confirm: 'Are you sure?' } %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
  <br>
<% end %>

app/views/info_emails/edit.html.erb
<h1>InfoEmails#edit</h1>
<p>Find me in app/views/info_emails/edit.html.erb</p>

app/views/info_emails/index.html.erb
<h1>InfoEmails#index</h1>
<p>Find me in app/views/info_emails/index.html.erb</p>
<% @info_emails.each do |ie| %>
	<%= ie.email %> <br>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Quicksand:300,400' %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Montserrat:400,700' %>
  <%= csrf_meta_tags %>
</head>


<body>
  <div class="container">
    <div class="navbar">
      <!-- this opens up the modal window on click -->
      <a id="modal-link" href="#dialog" >SIGNUP</a>
      <!-- creates a dynamic link_to Blog homepage -->
      <%= link_to "HOME", root_path, class: 'navlinks' %>
      <!-- creates a dynamic link_to about.html.erb -->
      <%= link_to "ABOUT", about_path, class: 'navlinks' %>
      <!-- creates a dynamic link_to contact.html.erb -->
      <a class="contact" href="mailto:monique.n.wolf@gmail.com">CONTACT</a>
       <!--  <div class="search">
          <%#= link_to "SEARCH", root_path %>
        </div> -->
    </div>

<div class="searchbar" class="ui-widget">
   <%= form_tag posts_path, :method => :get do %>
       <%= text_field_tag :search, params[:search], :id=>"posts", :placeholder=>"SEARCH" %>
       <% submit_tag "Search", :body => nil, :id=>"searchbutton" %>
   <% end %>
     </div>


    <div class="logo">
      <%= link_to root_path do %>
      <%= image_tag "veda_logo.png" %>
      <% end %>
    </div>


  	<div class="main_content">
      <div class="two-thirds">
        <!-- <div class="post_wrapper"> -->

        </div> <!-- this closes two-thirds -->
      </div>
      <!-- this is adding sidebar -->
      <!-- <div class="column_third"> -->
        <div class="row clearfix">
          <div class="sidebar_third">
            <h3>
            <%= link_to "SUBSTITUTES", substitutions_path %>
              <hr>
            <%= link_to "RECIPES", root_path %>
              <hr>
            </h3>

            <h4>VEDA, an ayurveda- based food blog
              <br>
              provides ingredient substitutions to
              <br>
              keep you in balance.
            </h4>
            <hr>
            <!-- this add my social media links -->
            <a class="icons" href="https://www.facebook.com/monique.wolf.14"><%= image_tag("FB_Icon.png", class: "smedia")  %></a>
            <a class="icons" href="https://instagram.com/moniquewolf"><%= image_tag("Insta_Icon.png", class: "smedia") %></a>
            <a class="icons" href="mailto:monique.n.wolf@gmail.com"><%= image_tag("Email_Icon.png", class: "smedia") %></a>


          </div> <!-- this closes sidebar -->
        <!-- </div> --> <!-- this closes clearfix -->
      <!-- </div> --> <!-- this closes column third -->

      <%= yield %>
    </div> <!-- this closes main content -->
    <br>
    <div class="back_bottom">
    <% if current_page?(root_path) %>
    <% elsif current_page?(about_path) %>
      <!-- <p>About</p> -->
    <% else %>
      <%= link_to "BACK TO ALL POSTS", root_path %>
    <% end %>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    </div>



  </div> <!-- this closes container -->







  <!-- // modal overlay -->
  <div id="overlay" class=""></div>
  <!-- // modal -->
  <div class="modal hidden" id="about-modal">
    <div id="close-about">x</div>
    <div class="modal-title">signup with veda</div>
    <br>
    <div class="modal-body">
      <div id="join">join our mailing list to receive new recipes delivered to your inbox</div>
    <!-- this is my modal window form -->
      <div class="hidden">
        <br>
        <%= form_for InfoEmail.new do |f|  %>
          <%= f.text_field :email, placeholder: " email address" %>
          <%= f.submit "submit" %>
        <% end %>
        <br>
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert") %>
        <% end %>
        <br>
      </div>
      <div class="modal-footer"></div>
    </div>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">

	<!-- this adds content to my about page -->
  <div class="two_thirds">
    <%= image_tag "sunsetFNL.png" %>
    <p>Hi, I’m Monique, an ever-curious food enthusiast who is also passionate about Ayurveda. I find the idea of food as medicine facinating and love that Ayurveda is the oldest form of holistic medicine. Each food has specific properties, i.e., walnuts are good for headaches (and coincidentally are shaped like a brain). Based on what dosha may be out of balance, you can acheive balance by catering your diet to specific foods to aid in a faster recovery. VEDA provides ingredient substitutions for recipes.</p>
  </div>
</div>

app/views/pages/sub.html.erb
<div id="page_wrapper">

<!-- this adds content to my about page -->
	<%= image_tag "substitutionsFNL.png" %>
  <div class="two_thirds">
    <h1>Here's a list of ingredient substitutions to consider while cooking</h1>
    <p class="two-col"> HONEY (heating)
    <br>
    Cooling substitute: maple syrup
    <br>
    <br>
    OLIVE OIL (heating)
    <br>
    Cooling substitutes: sunflower oil and coconut oil
    <br>
    <br>
    WALNUTS (drying)
    <br>
    Substitute: almonds  
  </div>
</div>

app/views/posts/_form.html.erb
<!-- this doesn't let you save a post without entering any data into the fields, you'll get errors -->
	<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
		<br>
		<%= f.label :photo %><br>
		<%= f.file_field :photo %><br>
		<br>
    <%= f.label :body %><br>
    <%= f.text_field :body %><br>
    <br>
		<%= f.submit %>
	<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>
	 
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% if current_user != nil %>
      <div class="buttons">
        <%= link_to "New Post", new_post_path if current_user.is_admin %>
        <%= link_to "Log Out", controller: "sessions", action: "destroy" %>
    </div>
<% end %>



<div class="two-thirds">
	<% @posts.each do |post| %>
				<!-- Adds photo -->
			<div class="photo">
				<%= image_tag post.photo.url  %>
			</div>
			<h2 class="title"><%= link_to post.title, post%></h2>
			<!-- <p class="date"><%#= post.created_at.strftime("%B %d, %Y") %></p> -->
	<% end %>
</div>
<br>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>
	 
	<%= form_for :post, url: posts_path do |f| %>
		<%= if@post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
			<ul>
				<li><%= msg %></li>
			<% end %>
		</div>
		<% end %>

		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
		<br>
		<%= f.label :body %><br>
		<%= f.text_field :body %><br>
		<br>
		<%= f.submit %>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="post_content">

	<!-- Adds photo -->
	<div id="photo" >
		<%= image_tag @post.photo.url %>
	</div>
	<!-- this adds the post title -->
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<!-- Adds the body content -->
	<p class="body">
		<%= @post.body %>
	</p>

	<!-- This shows time the post was created at -->
	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at)%> Ago
	<!-- this lets you edit the post -->
		|	<%= link_to 'Edit', edit_post_path(@post) %>
	<!-- this lets you delete the post -->
		| <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
	</p>

	<!-- this shows the comments -->
	<div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= @post.comments.each do |c| %>
    <%= c.body %>
    <% end %>
 
    <h1>Add a comment:</h1>
    <%= render "comments/form" %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
    <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New User', new_user_path %>
<br>
<%= link_to 'New Post', new_post_path %>

<button class="button"><%= link_to "Log Out", controller: "sessions", action: "destroy" %></button>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<%= image_tag @user.photo.url %>